### ISSUE TITLE
[1.2 Alpha] General Sync Issues

### ISSUE THREAD

**Issue by Firstmada** [inferno-collection/Ladders#2]
- Carrying ladder from a vehicle is a bit 'jumpy/laggy' for those watching the player who is carrying it.

- Animations climbing up/down when spectating another player using the ladder is not at the same pitch/rotation to the ladder and instead to these watching appear to be floating off it and climbing vertically into the sky.

- The person who takes out the ladder and places it, must be the one to pick it up and return it otherwise if someone else [who did not place it originally] will only see it move and it will be static in place for everyone else with no collection/climb prompts.

**Comment by cm8263** [comment]
Was aware of the first two, but not the third, I will look into it, thanks.

**Comment by cm8263** [comment]
Attempted to resolve in https://github.com/inferno-collection/Ladders/commit/aeb4014921c15b52104ef8aaf91d15ada18c7ff2.

**Comment by cm8263** [comment]
All three resolved or greatly improved in https://github.com/inferno-collection/Ladders/commit/cf1c1ff3c92d8bdbac024ff23836b33ece3f83c5.

https://github.com/inferno-collection/Ladders/releases/tag/v1.3-beta
